### ISSUE TITLE
dbus wire format error: variant signature is empty

### ISSUE THREAD

**Issue by joseffilzmaier** [Wifx/gonetworkmanager#3]
Hello!

I have been playing around with your library and think it's quite nice, as i need similar functionality.

I did, however run into a problem: When calling `GetSettings()` on the Connection object:
I do get the error
**wire format error: variant signature is empty**
After i get the error the dbus connection also seems to be flawed.

disclaimer: I'm using NetworkManager 1.20.0
All other functions are working fine.

I don't think the dbus interface changed from nm 1.16 to 1.20, so it should be able to parse the dbus response

Any idea on this?

**Comment by mullerch** [comment]
Hi,

My first guess is that your dbus server (the NetworkManager) returns a settings structure with a property who's missing variant signature. Without this information godbus cannot decode the information.

As NM 1.20 has been release a few day ago only I would suspect a bug there. You should check with other dbus tools (e.g. CLI) to see if the same problem occurs.

**Comment by joseffilzmaier** [comment]
I managed to solve the problem by updating my go module godbus/dbus to the master branch. It was somehow outdated in my go.mod/go.sum file

It now also works with NetworkManager 1.20, FYI

Thanks for your tips they gave me a hint in the right direction!
